import { mapper } from "@root/core/mapper/auto-mapper";
import type { OrderModel } from "@features/order/model/order.model";

mapper.register<OrderModel>({
  name: "Order",
  dtoToModelNaming: "snake_to_camel",
  modelToDtoNaming: "camel_to_snake",
  defaultModel: () => ({
    id: 0,
    code: "",
    promotionCode: null,
    promotionCodeId: null,
    customFields: null,
    customerId: 0,
    customerName: "",
    clinicId: null,
    clinicName: null,
    dentistId: null,
    dentistName: null,
    patientId: null,
    patientName: null,
    refUserId: null,
    refUserName: null,
    statusLatest: "",
    codeLatest: "",
    priorityLatest: "",
    processIdLatest: null,
    processNameLatest: null,
    productId: 0,
    productName: "",
    quantity: 0,
    totalPrice: 0,
    deliveryDate: null,
    imageUrl: null,
    proofImageUrl: null,
    deliveryProofs: null,
    orderDeliveryProofs: null,
    remakeCount: 0,
    remakeType: "",
    createdAt: "",
    updatedAt: "",
    latestOrderItemUpsert: {
      dto: {
        id: 0,
        orderId: 0,
        parentItemId: null,
        code: "",
        codeOriginal: "",
        qrCode: null,
        isCash: false,
        isCredit: false,
        remakeCount: 0,
        customFields: null,
        createdAt: "",
        updatedAt: "",
        // product
        productId: 0,
        productName: "",
        imageUrl: null,
        proofImageUrl: null,
        deliveryProofs: null,
        orderDeliveryProofs: null,
        // products
        products: null,
        // materials
        consumableMaterials: null,
        loanerMaterials: null,
      }
    },
    latestOrderItem: {
      // general
      id: 0,
      orderId: 0,
      parentItemId: null,
      customFields: null,
      isCash: false,
      isCredit: false,
      createdAt: "",
      updatedAt: "",
      // order
      code: "",
      codeOriginal: "",
      qrCode: null,
      remakeCount: 0,
      // product
      productId: 0,
      productName: "",
      imageUrl: null,
      proofImageUrl: null,
      deliveryProofs: null,
      orderDeliveryProofs: null,
      // products
      products: null,
      // materials
      consumableMaterials: null,
      loanerMaterials: null,
    },
  }),
});
