import { mapper } from "@core/mapper/auto-mapper";

mapper.register({
  name: "Dashboard",
  dtoToModelNaming: "snake_to_camel",
  modelToDtoNaming: "camel_to_snake",
  defaultModel: () => ({
    id: 0,
    avgDays: 0,
    deltaDays: 0,
    rate: 0,
    deltaRate: 0,
    value: 0,
    delta: 0,
    code: "",
    dentist: "",
    patient: "",
    deliveryAt: "",
    createdAt: "",
    ageDays: 0,
    dueType: "today",
    priority: "standard",
    status: "received",
    deliveryStatus: "pending",
    label: "",
    count: 0,
    target: 0,
    color: "primary",
    helper: "",
    totalRevenue: 0,
    orderItemsCount: 0,
    prevRevenue: 0,
    growthPercent: null,
    date: "",
    revenue: 0,
  }),
  defaultDto: () => ({
    id: 0,
    department_id: null,
    from_date: "",
    to_date: "",
    previous_from_date: "",
    previous_to_date: "",
    avg_days: 0,
    delta_days: 0,
    rate: 0,
    delta_rate: 0,
    value: 0,
    delta: 0,
    code: "",
    dentist: "",
    patient: "",
    delivery_at: "",
    created_at: "",
    age_days: 0,
    due_type: "today",
    priority: "standard",
    status: "received",
    delivery_status: "pending",
    label: "",
    count: 0,
    target: 0,
    color: "primary",
    helper: "",
    total_revenue: 0,
    order_items_count: 0,
    prev_revenue: 0,
    growth_percent: null,
    date: "",
    revenue: 0,
  }),
});
